### ISSUE TITLE
MEGA file, megasync, not found

### ISSUE THREAD

**Issue by talesam** [jorgicio/jorgicio-gentoo#1]
See the output of my log, the file megasync was reached in any server.

https://pastebin.sabayon.org/pastie/17066

Was updated to version .30 *
https://mega.co.nz/linux/MEGAsync/xUbuntu_14.04/amd64/

**Comment by samuraiii** [comment]
Hi,
There is another problem with Manifest file for net-misc/megasync
When I try to install client (v 1.0.39 i386 - others do no have any distfile available, haven't tried x64) it stops by complaining about filesize of downloaded distfile (checksusm also do not match).
(Possibly) New manifest data looks like this:
DIST megasync_1.0.39_i386.deb 1692326 SHA256 0649b4a35c82bf0ce3783a32db0be043679f3e6f27860fe326425f6af3f78fd1 SHA512 bfda53d6a3431b8d6b404595279f410ffa7d477f190265328da17f82b026c17cf605033e335cb001af882c44a90f51c12a9ec0599d1163f63ea1f2471e8337b9 WHIRLPOOL d05285a7a9047b3b2e6f7b6a13217237b3457af102a9ec2b7c716026f58bbfc4f75ea6b821f03adcef39c8aba8bf0f3a41d396607f28c3252993f0eed0841a7e
Hope this will help
S

**Comment by talesam** [comment]
I also could not

>>> Downloading 'https://mega.co.nz/linux/MEGAsync/xUbuntu_14.04/amd64/megasync_1.0.39_amd64.deb'
--2015-03-05 00:51:02--  https://mega.co.nz/linux/MEGAsync/xUbuntu_14.04/amd64/megasync_1.0.39_amd64.deb
Resolving mega.co.nz... 154.53.224.146, 2001:978:2:aa::24:2
Connecting to mega.co.nz|154.53.224.146|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-03-05 00:51:03 ERROR 404: Not Found.

!!! Couldn't download 'megasync_1.0.39_amd64.deb'. Aborting.
 * Fetch failed for 'net-misc/megasync-1.0.39', Log file:
 *  '/var/tmp/portage/net-misc/megasync-1.0.39/temp/build.log'

>>> Failed to emerge net-misc/megasync-1.0.39, Log file:

>>>  '/var/tmp/portage/net-misc/megasync-1.0.39/temp/build.log'

 * Messages for package net-misc/megasync-1.0.39:

 * Fetch failed for 'net-misc/megasync-1.0.39', Log file:
 *  '/var/tmp/portage/net-misc/megasync-1.0.39/temp/build.log'

**Comment by jorgicio** [comment]
Try again. Here I got no problems.

Also, I was on vacations, so that was I wasn't replied before.

**Comment by talesam** [comment]
The problem is no longer the 1.0.39 version, now is version 2.0, see here: https://mega.co.nz/linux/MEGAsync/xUbuntu_14.04/amd64/

**Comment by talesam** [comment]
Hi, see...

No such file ‘megasync_2.0.0_amd64.deb’.

>>> Resuming download...
>>> Downloading 'https://mega.co.nz/linux/MEGAsync/xUbuntu_14.04/amd64/megasync_2.0.0_amd64.deb'
--2015-06-24 11:34:21--  https://mega.co.nz/linux/MEGAsync/xUbuntu_14.04/amd64/megasync_2.0.0_amd64.deb
Resolving mega.co.nz... 154.53.224.146, 2001:978:2:aa::24:2
Connecting to mega.co.nz|154.53.224.146|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1700662 (1,6M) [application/x-deb]
Saving to: ‘/usr/portage/distfiles/megasync_2.0.0_amd64.deb’

/usr/portage/distfi 100%[=====================>]   1,62M   477KB/s   in 3,5s   

2015-06-24 11:34:27 (477 KB/s) - ‘/usr/portage/distfiles/megasync_2.0.0_amd64.deb’ saved [1700662/1700662]

!!! Fetched file: megasync_2.0.0_amd64.deb VERIFY FAILED!
!!! Reason: Failed on SHA256 verification
!!! Got:      454f1d8101cb4d2edc2aee78b14b9f2670f7967f5fbae4c0db4aee278702cccd
!!! Expected: b83b5ef84dcf8215772781a494fda0246860f9328577318ccac3613c871157e3
Refetching... File renamed to '/usr/portage/distfiles/megasync_2.0.0_amd64.deb._checksum_failure_.ntHNoF'

!!! Couldn't download 'megasync_2.0.0_amd64.deb'. Aborting.
 * Fetch failed for 'net-misc/megasync-2.0.0-r1', Log file:
 *  '/var/tmp/portage/net-misc/megasync-2.0.0-r1/temp/build.log'

>>> Failed to emerge net-misc/megasync-2.0.0-r1, Log file:

>>>  '/var/tmp/portage/net-misc/megasync-2.0.0-r1/temp/build.log'

 * Messages for package net-misc/megasync-2.0.0-r1:

 * Fetch failed for 'net-misc/megasync-2.0.0-r1', Log file:
 *  '/var/tmp/portage/net-misc/megasync-2.0.0-r1/temp/build.log'
neit talesam #

**Comment by jorgicio** [comment]
Mmmm... I don't know what's wrong with you, but I tried here on my notebook, and it works. Check your FETCHCOMMAND, and try again.

**Comment by talesam** [comment]
http://pastebin.sabayon.org/pastie/17388

I'm already with version 2.0 installed, and the repository has 2.0-r1 , is that this is not the problem ?

**Comment by jorgicio** [comment]
In fact, yes, the -r1 solves that problem. Please, update periodically the layman overlays with layman -S.

**Comment by talesam** [comment]
squeegee every day ...
emerge --sync && layman -S && eix-sync -a

**Comment by jorgicio** [comment]
Create or add this line to your /etc/eix-sync.conf:
*
(Yes, just an asterisk)
Then, you just do eix-sync, and you're done. You don't need anything else.

**Comment by talesam** [comment]
After doing this I need not always run this command:
emerge --sync && layman -S && eix-sync -a

**Comment by jorgicio** [comment]
No, you don't need to do this anymore. Just eix-sync, because it doesn't only sync you Portage tree, but also the overlays you added with Layman.

**Comment by talesam** [comment]
Thank you very much;)

**Comment by michaelkempff** [comment]
Hi jorgicio, 

The megasync package refuses to install, i think the package url is outdated in the ebuild. This is the output of "emerge --ask net-misc/megasync":


>>> Verifying ebuild manifests

>>> Emerging (1 of 1) net-misc/megasync-2.3.1::jorgicio
>>> Downloading 'http://distfiles.gentoo.org/distfiles/megasync_2.3.1_amd64.deb'
--2016-01-17 18:15:12--  http://distfiles.gentoo.org/distfiles/megasync_2.3.1_amd64.deb
Resolving distfiles.gentoo.org... 156.56.247.195, 140.211.166.134, 137.226.34.46, ...
Connecting to distfiles.gentoo.org|156.56.247.195|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-01-17 18:15:12 ERROR 404: Not Found.

>>> Downloading 'https://mega.co.nz/linux/MEGAsync/xUbuntu_14.04/amd64/megasync_2.3.1_amd64.deb'
--2016-01-17 18:15:12--  https://mega.co.nz/linux/MEGAsync/xUbuntu_14.04/amd64/megasync_2.3.1_amd64.deb
Resolving mega.co.nz... 154.53.224.118, 2001:978:2:aa::1d:2
Connecting to mega.co.nz|154.53.224.118|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-01-17 18:15:14 ERROR 404: Not Found.

!!! Couldn't download 'megasync_2.3.1_amd64.deb'. Aborting.
 * Fetch failed for 'net-misc/megasync-2.3.1', Log file:
 *  '/var/tmp/portage/net-misc/megasync-2.3.1/temp/build.log'

>>> Failed to emerge net-misc/megasync-2.3.1, Log file:

>>>  '/var/tmp/portage/net-misc/megasync-2.3.1/temp/build.log'

 * Messages for package net-misc/megasync-2.3.1:

 * Fetch failed for 'net-misc/megasync-2.3.1', Log file:
 *  '/var/tmp/portage/net-misc/megasync-2.3.1/temp/build.log'

**Comment by jorgicio** [comment]
Fixed. Version upgraded.

**Comment by michaelkempff** [comment]
Thanks!
I managed to install the package by hand. But using your overlay is more comfortable :-)
I'll try tomorow.

**Comment by michaelkempff** [comment]
Sorry, it took a while fore me to try (busy with work). But it's still not working. The url to the deb file is wrong, it has to be: 

https://mega.nz/linux/MEGAsync/xUbuntu_14.04/amd64/megasync-xUbuntu_14.04_amd64.deb

Thanks in advance!

**Comment by jorgicio** [comment]
I didn't know that URL. I hope this doesn't fail at digest when a future release is freed. Well, fixed. Resync and you're done.

**Comment by michaelkempff** [comment]
Perfect, it's working now. Thanks a lot! In case it's failing in the future, i'll let you know.

**Comment by vasettoo** [comment]
Hi, Jorgicio! I appreciate your hard work on MEGASync, which I've been using almost for an year. Recently reinstalled my gentoo installation and tried to make use of MEGA again. But after adding your repo and unmasking the needed packages (nautilus-megasync & megasync) I ended up this error:
`Downloading 'https://mega.nz/linux/MEGAsync/xUbuntu_14.04/amd64/megasync-xUbuntu_14.04_amd64.deb'
--2016-03-02 20:49:54--  https://mega.nz/linux/MEGAsync/xUbuntu_14.04/amd64/megasync-xUbuntu_14.04_amd64.deb
Resolving mega.nz... 154.53.224.142, 154.53.224.138, 154.53.224.166, ...
Connecting to mega.nz|154.53.224.142|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1680532 (1,6M) [application/x-deb]
Saving to: ‘/usr/portage/distfiles/megasync_2.6.1_amd64.deb’

     0K .......... .......... .......... .......... ..........  3% 1,30M 1s
    50K .......... .......... .......... .......... ..........  6% 1,38M 1s
   100K .......... .......... .......... .......... ..........  9% 1,49M 1s
   150K .......... .......... .......... .......... .......... 12% 1,46M 1s
   200K .......... .......... .......... .......... .......... 15% 4,57M 1s
   250K .......... .......... .......... .......... .......... 18% 1,57M 1s
   300K .......... .......... .......... .......... .......... 21% 1,53M 1s
   350K .......... .......... .......... .......... .......... 24% 1,47M 1s
   400K .......... .......... .......... .......... .......... 27% 3,42M 1s
   450K .......... .......... .......... .......... .......... 30% 1,46M 1s
   500K .......... .......... .......... .......... .......... 33% 2,00M 1s
   550K .......... .......... .......... .......... .......... 36% 3,49M 1s
   600K .......... .......... .......... .......... .......... 39% 1,53M 1s
   650K .......... .......... .......... .......... .......... 42% 9,77M 0s
   700K .......... .......... .......... .......... .......... 45% 1,52M 0s
   750K .......... .......... .......... .......... .......... 48% 1,85M 0s
   800K .......... .......... .......... .......... .......... 51% 3,77M 0s
   850K .......... .......... .......... .......... .......... 54% 1,63M 0s
   900K .......... .......... .......... .......... .......... 57% 8,09M 0s
   950K .......... .......... .......... .......... .......... 60% 1,58M 0s
  1000K .......... .......... .......... .......... .......... 63% 11,6M 0s
  1050K .......... .......... .......... .......... .......... 67% 1,67M 0s
  1100K .......... .......... .......... .......... .......... 70% 8,31M 0s
  1150K .......... .......... .......... .......... .......... 73% 1,53M 0s
  1200K .......... .......... .......... .......... .......... 76% 10,4M 0s
  1250K .......... .......... .......... .......... .......... 79% 1,82M 0s
  1300K .......... .......... .......... .......... .......... 82% 6,06M 0s
  1350K .......... .......... .......... .......... .......... 85% 2,57M 0s
  1400K .......... .......... .......... .......... .......... 88% 3,24M 0s
  1450K .......... .......... .......... .......... .......... 91% 3,06M 0s
  1500K .......... .......... .......... .......... .......... 94% 3,09M 0s
  1550K .......... .......... .......... .......... .......... 97% 6,11M 0s
  1600K .......... .......... .......... .......... .         100% 3,13M=0,7s

2016-03-02 20:49:55 (2,27 MB/s) - ‘/usr/portage/distfiles/megasync_2.6.1_amd64.deb’ saved [1680532/1680532]

!!! Fetched file: megasync_2.6.1_amd64.deb VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      1680532
!!! Expected: 1909086
Refetching... File renamed to '/usr/portage/distfiles/megasync_2.6.1_amd64.deb._checksum_failure_.OQB0rV'

!!! Couldn't download 'megasync_2.6.1_amd64.deb'. Aborting.
 * Fetch failed for 'net-misc/megasync-2.6.1', Log file:
 *  '/tmp/portage/net-misc/megasync-2.6.1/temp/build.log'

 * GNU info directory index is up-to-date.
`
Is it a problem that I didn't use layman but repos.conf instead:

`  GNU nano 2.4.3     Файл: /etc/portage/repos.conf/jorgicio.conf                

[jorgicio]

# Various utility ebuilds for Gentoo (Mega Sync)
# Maintainer: Jorgicio (http://jorgicio.net)

location = /usr/local/portage/jorgicio
sync-type = git
sync-uri = https://github.com/jorgicio/jorgicio-gentoo.git
priority = 50
auto-sync = yes`

All help is welcome.
Best regards!

**Comment by jorgicio** [comment]
Hi! Thank you! And fixed. Try again.

**Comment by vasettoo** [comment]
Thank you! Everything works now.
Best regards!

**Comment by michaelkempff** [comment]
Hi Jogicio,

After reinstalling my gentoo box, i'm encountering the following issue with megasync:

megasync: error while loading shared libraries: libQtDBus.so.4: cannot open shared object file: No such file or directory

I'm not sure if it has anything to do with your overlay, but searching the web did not gave me any results.

I hope you can help.

Best regards

**Comment by michaelkempff** [comment]
Thanks a lot for your reply!

I allready tried to find the file with "eqeury -b libQtDBus.so.4" but with no results.

After reinstalling qtdbus:4 i get the following error message when trying to start megasync:

megasync: /usr/lib64/libcrypto.so.1.0.0: no version information available (required by megasync)
megasync: /usr/lib64/libssl.so.1.0.0: no version information available (required by megasync)
megasync: /usr/lib64/libssl.so.1.0.0: no version information available (required by megasync)
megasync: symbol lookup error: megasync: undefined symbol: _ZN8CryptoPP15DEFAULT_CHANNELE
