### ISSUE TITLE
Failed to build binary package for app-editors/atom-1.0.19

### ISSUE THREAD

**Issue by fusion809** [jorgicio/jorgicio-gentoo#27]
Hi, 

I ran `emerge -B =app-editors/atom-1.0.19` and it gave me the error:

``` sh
npm WARN package.json atom-build@ No license field.
npm ERR! cb() never called!
 * ERROR: app-editors/atom-1.0.19::jorgicio failed (compile phase):
 *   Failed to compile
 * 
 * Call stack:
 *     ebuild.sh, line  90:  Called src_compile
 *   environment, line 3727:  Called die
 * The specific snippet of code:
 *       ./script/build --verbose --build-dir "${T}" || die "Failed to compile";
 * 
 * If you need support, post the output of `emerge --info '=app-editors/atom-1.0.19::jorgicio'`,
 * the complete build log and the output of `emerge -pqv '=app-editors/atom-1.0.19::jorgicio'`.
 * The complete build log is located at '/var/tmp/portage/app-editors/atom-1.0.19/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-editors/atom-1.0.19/temp/environment'.
 * Working directory: '/var/tmp/portage/app-editors/atom-1.0.19/work/atom-1.0.19'
 * S: '/var/tmp/portage/app-editors/atom-1.0.19/work/atom-1.0.19'

>>> Failed to emerge app-editors/atom-1.0.19, Log file:

>>>  '/var/tmp/portage/app-editors/atom-1.0.19/temp/build.log'

 * Messages for package app-editors/atom-1.0.19:

 * ERROR: app-editors/atom-1.0.19::jorgicio failed (compile phase):
 *   Failed to compile
 * 
 * Call stack:
 *     ebuild.sh, line  90:  Called src_compile
 *   environment, line 3727:  Called die
 * The specific snippet of code:
 *       ./script/build --verbose --build-dir "${T}" || die "Failed to compile";
 * 
 * If you need support, post the output of `emerge --info '=app-editors/atom-1.0.19::jorgicio'`,
 * the complete build log and the output of `emerge -pqv '=app-editors/atom-1.0.19::jorgicio'`.
 * The complete build log is located at '/var/tmp/portage/app-editors/atom-1.0.19/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-editors/atom-1.0.19/temp/environment'.
 * Working directory: '/var/tmp/portage/app-editors/atom-1.0.19/work/atom-1.0.19'
 * S: '/var/tmp/portage/app-editors/atom-1.0.19/work/atom-1.0.19'
```

[Here](http://pastebin.com/nFf3d7RD)'s the output of `emerge --info...`. While here's the output of the `-pqv` command: `[ebuild  N    ] app-editors/atom-1.0.19`. While [here](http://pastebin.com/Y86rrzFF) is my build.log file. 

Thanks for your time,
Brenton

**Comment by jorgicio** [comment]
I added a patch, but I won't assure it builds a binary (I don't use that option), but it may do.
Try again.

**Comment by jorgicio** [comment]
Fixed!

**Comment by fusion809** [comment]
Not quite fixed. 

```sh
>>> Compiling source in /var/tmp/portage/app-editors/atom-1.0.19/work/atom-1.0.19 ...
Node: v0.12.7
npm: v2.11.3
Installing build modules...
npm WARN package.json atom-build@ No license field.
npm ERR! cb() never called!
 * ERROR: app-editors/atom-1.0.19::jorgicio failed (compile phase):
 *   Failed to compile
 * 
 * Call stack:
 *     ebuild.sh, line  93:  Called src_compile
 *   environment, line 3702:  Called die
 * The specific snippet of code:
 *       ./script/build --verbose --build-dir "${T}" || die "Failed to compile";
 * 
 * If you need support, post the output of `emerge --info '=app-editors/atom-1.0.19::jorgicio'`,
 * the complete build log and the output of `emerge -pqv '=app-editors/atom-1.0.19::jorgicio'`.
 * The complete build log is located at '/var/tmp/portage/app-editors/atom-1.0.19/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-editors/atom-1.0.19/temp/environment'.
 * Working directory: '/var/tmp/portage/app-editors/atom-1.0.19/work/atom-1.0.19'
 * S: '/var/tmp/portage/app-editors/atom-1.0.19/work/atom-1.0.19'

>>> Failed to emerge app-editors/atom-1.0.19, Log file:

>>>  '/var/tmp/portage/app-editors/atom-1.0.19/temp/build.log'

 * Messages for package app-editors/atom-1.0.19:

 * ERROR: app-editors/atom-1.0.19::jorgicio failed (compile phase):
 *   Failed to compile
 * 
 * Call stack:
 *     ebuild.sh, line  93:  Called src_compile
 *   environment, line 3702:  Called die
 * The specific snippet of code:
 *       ./script/build --verbose --build-dir "${T}" || die "Failed to compile";
 * 
 * If you need support, post the output of `emerge --info '=app-editors/atom-1.0.19::jorgicio'`,
 * the complete build log and the output of `emerge -pqv '=app-editors/atom-1.0.19::jorgicio'`.
 * The complete build log is located at '/var/tmp/portage/app-editors/atom-1.0.19/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-editors/atom-1.0.19/temp/environment'.
 * Working directory: '/var/tmp/portage/app-editors/atom-1.0.19/work/atom-1.0.19'
 * S: '/var/tmp/portage/app-editors/atom-1.0.19/work/atom-1.0.19'
```

**Comment by fusion809** [comment]
@jorgicio Not quite fixed. I'm now getting the error:
```sh
>>> Compiling source in /var/tmp/portage/app-editors/atom-1.0.19/work/atom-1.0.19 ...
Node: v0.12.7
npm: v2.11.3
Installing build modules...
npm WARN package.json atom-build@ No license field.
npm ERR! cb() never called!
 * ERROR: app-editors/atom-1.0.19::jorgicio failed (compile phase):
 *   Failed to compile
 * 
 * Call stack:
 *     ebuild.sh, line  93:  Called src_compile
 *   environment, line 3702:  Called die
 * The specific snippet of code:
 *       ./script/build --verbose --build-dir "${T}" || die "Failed to compile";
 * 
 * If you need support, post the output of `emerge --info '=app-editors/atom-1.0.19::jorgicio'`,
 * the complete build log and the output of `emerge -pqv '=app-editors/atom-1.0.19::jorgicio'`.
 * The complete build log is located at '/var/tmp/portage/app-editors/atom-1.0.19/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-editors/atom-1.0.19/temp/environment'.
 * Working directory: '/var/tmp/portage/app-editors/atom-1.0.19/work/atom-1.0.19'
 * S: '/var/tmp/portage/app-editors/atom-1.0.19/work/atom-1.0.19'

>>> Failed to emerge app-editors/atom-1.0.19, Log file:

>>>  '/var/tmp/portage/app-editors/atom-1.0.19/temp/build.log'

 * Messages for package app-editors/atom-1.0.19:

 * ERROR: app-editors/atom-1.0.19::jorgicio failed (compile phase):
 *   Failed to compile
 * 
 * Call stack:
 *     ebuild.sh, line  93:  Called src_compile
 *   environment, line 3702:  Called die
 * The specific snippet of code:
 *       ./script/build --verbose --build-dir "${T}" || die "Failed to compile";
 * 
 * If you need support, post the output of `emerge --info '=app-editors/atom-1.0.19::jorgicio'`,
 * the complete build log and the output of `emerge -pqv '=app-editors/atom-1.0.19::jorgicio'`.
 * The complete build log is located at '/var/tmp/portage/app-editors/atom-1.0.19/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-editors/atom-1.0.19/temp/environment'.
 * Working directory: '/var/tmp/portage/app-editors/atom-1.0.19/work/atom-1.0.19'
 * S: '/var/tmp/portage/app-editors/atom-1.0.19/work/atom-1.0.19'
```
[Here](http://pastebin.com/JxK62xfb)'s my build.log file.

**Comment by jorgicio** [comment]
Sorry, I didn't notice that, as I don't use Atom. Anyways, I'll check it later.

**Comment by jorgicio** [comment]
As I don't maintain the atom ebuild anymore, I'll close this.
