### ISSUE TITLE
Patch telegram

### ISSUE THREAD

**Issue by tux-mind** [jorgicio/jorgicio-gentoo#79]
Please apply a patch that will fix the assertion error on unknown messages types: https://github.com/vysheng/tg/issues/904 .

Best regards, tux_mind.

**Comment by jorgicio** [comment]
The issue was fixed upstream, but I had to do the patch as a backport to the 1.3.1 version.
Fixed in 1.3.1-r1 version.

Thanks and best regards

**Comment by tux-mind** [comment]
Thank you for the quick fix :blush: 
Sadly it seems to not work, even if the patch is applied correctly the `structure.c` file still have the assertion ( just checked with a manual run of `ebuild` ).

epatch.log:

```
PATCH: /var/lib/layman/jorgicio/net-im/telegram-cli/files/telegram-cli-1.3.1-assertion-issue.patch
CMD: patch -p1 -g0 -E --no-backup-if-mismatch 
PWD: /var/tmp/portage/net-im/telegram-cli-1.3.1-r1/work/tg-1.3.1
```

build.log:

```
 * Package:    net-im/telegram-cli-1.3.1-r1
 * Repository: jorgicio
 * Maintainer: jpizarrocallejas@gmail.com
 * USE:        abi_x86_64 amd64 elibc_glibc json kernel_linux lua python_targets_python2_7 python_targets_python3_4 userland_GNU
 * FEATURES:   preserve-libs sandbox splitdebug userpriv usersandbox
 * Package:    net-im/telegram-cli-1.3.1-r1
 * Repository: jorgicio
 * Maintainer: jpizarrocallejas@gmail.com
 * USE:        abi_x86_64 amd64 elibc_glibc json kernel_linux lua python_targets_python2_7 python_targets_python3_4 userland_GNU
 * FEATURES:   preserve-libs sandbox splitdebug userpriv usersandbox
>>> Unpacking source...
>>> Unpacking telegram-cli-1.3.1.tar.gz to /var/tmp/portage/net-im/telegram-cli-1.3.1-r1/work
>>> Unpacking tgl-20150514.tar.gz to /var/tmp/portage/net-im/telegram-cli-1.3.1-r1/work
>>> Unpacking tl-parser-20141119.tar.gz to /var/tmp/portage/net-im/telegram-cli-1.3.1-r1/work
>>> Source unpacked in /var/tmp/portage/net-im/telegram-cli-1.3.1-r1/work
>>> Preparing source in /var/tmp/portage/net-im/telegram-cli-1.3.1-r1/work/tg-1.3.1 ...
 * Applying telegram-cli-1.3.1-assertion-issue.patch ...
 [ ok ]
>>> Source prepared.
```

**Comment by jorgicio** [comment]
Sorry, wrong line xD
Patch fixed and also fixed the issue ;)

**Comment by tux-mind** [comment]
Great, it is now working :wink: 
Thank you again for your time :blush:
